# Generated by Django 5.2.7 on 2025-11-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="community_avatars/"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="community_banners/"
                    ),
                ),
            ],
        ),
    ]
