# Generated by Django 5.2.7 on 2025-11-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
