# Generated by Django 5.2.8 on 2025-11-13 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
