# Generated by Django 5.2.7 on 2025-11-03 13:31

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_alter_community_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=communities.models.community_avatar_path,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=communities.models.community_banner_path,
            ),
        ),
    ]
