# Generated by Django 5.2.8 on 2025-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_community_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
