# flake8: noqa: E501

"""
Django settings for asw_pd11e_dj project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8qu^s(p(l2xfx*u9b1qe%uucei#%9@q!lv$d==t5l!lk(+u2qs"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["asw-pd11e-dj.onrender.com", "localhost", "127.0.0.1"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "blog",
    "communities",
    "accounts",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

SITE_ID = 1

MIDDLEWARE = [
    "allauth.account.middleware.AccountMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': "392869001985-s2nnjrdrt2kv36hirrchk73t17gd84tu.apps.googleusercontent.com",
            'secret': "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",
            'key': ''
        }
    }
}

ROOT_URLCONF = "asw_pd11e_dj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

WSGI_APPLICATION = "asw_pd11e_dj.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (local fallback, but overridden by S3)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# -------------------------------
# AWS S3 Settings for Media Files
# -------------------------------
AWS_ACCESS_KEY_ID = "ASIAQ2FMKCBPUWS6UUCZ"
AWS_SECRET_ACCESS_KEY = "Dy5xaoYZ7IgtMQuu690R2r208dNK2h704yXr5Ukn"
AWS_SESSION_TOKEN = ("IQoJb3JpZ2luX2VjEHMaCXVzLXdlc3QtMiJGMEQCIFbRwiBeWEkhJHfbxk+UpAT90UtOTITTbO8dr0SYn7i8AiBFzMwZKQHawOvOMD8x7zv0U/"
                     "sEiDuB2MDuba3rWywU2iq7Agg7EAAaDDA1NjE5NTk0NDU0MyIMmC/J5C+0lUY21pQvKpgCgYc8GQuNy+Mdqf6K5tgPu6Q4SpbQodTAp5GSl7KmQMLQviFTR377msGuOso5n/"
                     "RNkgfmBpKccAa5Qx77uNXU7a4sXWevBNsKYpFXUNtgx0mnTdL7GoarcqkobLZfI3Uxu8zFy4wLsf6qWp3DjnJe2zZixXGgAJD6Jy283MECUbtEk9tK3pp5gkZhtsttxEJff+"
                     "IfDpN5EruigjGGRh1FzGRC2oORqbgoKbC6feV/+pVVhPr2xcFpyqF2vMnGWYPHiK7gP+g4mrPa8qeKIlOoHcjuQDBqVAo59mal/G3qZoVCmqHXvrQfuTz2JdBeXuRgP1tcrfAl/"
                     "yAXuiIo+cl5NTtPQJ0dIo+bIg9V4guFddEM399uwzqjhDCmn9PIBjqeAT3cr7BC4z4lzO+rQOXkBtEMbF9X0W1MVPMwHHDnSl64NBH0nG0dLiN3q1hvbGORMOufktiqUfqI/gngWeOAOMcduzgF801RM7Gt6ilyonxRDmezSuHBjpCk1IWtAGcy4Q9/zYDpOIPZPPhbDucp0hkMJkv/02o2zftRCWp9xj+PP4kJaJK5uhJ0JFY3icUqNvl3xQZIt2rSX93SGAy1")

AWS_STORAGE_BUCKET_NAME = "asw-pd11e-dj"
AWS_S3_REGION_NAME = "us-east-1"

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
