# Generated by Django 5.2.8 on 2025-11-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("blog", "0006_merge_20251112_2257"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_posts",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="blog.post"
            ),
        ),
    ]
