# Generated by Django 5.2.8 on 2025-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_saved_posts"),
        ("blog", "0007_merge_20251112_2320"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_comments",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by_comments", to="blog.comment"
            ),
        ),
    ]
