# Generated by Django 5.2.8 on 2025-11-16 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_saved_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="api_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
