# Generated by Django 5.2.8 on 2025-11-16 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="api_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
