# Generated by Django 5.2.7 on 2025-11-05 17:45

import blog.models.post
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=5000)),
                ("author", models.CharField(max_length=100)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("votes", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.post.post_image_path,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostsCommunities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communities.community",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts Communities",
                "unique_together": {("post", "community")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="communities",
            field=models.ManyToManyField(
                related_name="posts",
                through="blog.PostsCommunities",
                to="communities.community",
            ),
        ),
    ]
