# Generated by Django 5.2.7 on 2025-11-05 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content"),
        ("communities", "0003_alter_community_avatar_alter_community_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="votes",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PostsCommunities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communities.community",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts Communities",
                "unique_together": {("post", "community")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="communities",
            field=models.ManyToManyField(
                related_name="posts",
                through="blog.PostsCommunities",
                to="communities.community",
            ),
        ),
    ]
