# Generated by Django 5.2.7 on 2025-11-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
