# Generated by Django 5.2.8 on 2025-11-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=5000),
        ),
    ]
