# Generated by Django 5.2.7 on 2025-11-05 09:33

import blog.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_votes_postscommunities_post_communities"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=blog.models.post.post_image_path
            ),
        ),
    ]
