# Generated by Django 5.2.7 on 2025-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
