# Generated by Django 5.2.8 on 2025-11-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_author_alter_comment_content_and_more"),
        ("blog", "0004_alter_comment_content"),
    ]

    operations = []
