# Generated by Django 5.2.8 on 2025-11-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_merge_20251112_2042"),
        ("blog", "0005_votecomment_votepost"),
    ]

    operations = []
