# Generated by Django 5.2.8 on 2025-11-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_merge_20251112_2155"),
        ("blog", "0006_merge_20251112_2257"),
    ]

    operations = []
